framework:
    secret: ThisTokenIsNotSoSecretChangeIt
    assets: ~
    templating:
        engines: ['twig']
    translator:
        fallbacks: ['%locale%']
        paths:
            - '%kernel.root_dir%/../inc/locale/'
    
parameters:
    locale:     en
   
services:
    app.locale_listener:
        class: Runalyze\Bundle\CoreBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }