security:
    encoders:
        Runalyze\Bundle\CoreBundle\Entity\Account:
            id: app.sha256salted_encoder

    providers:
        runalyzeuser:
            entity:
                class: CoreBundle:Account

    firewalls:
        default:
            anonymous: ~
            http_basic: ~
            provider:  runalyzeuser
            logout:
                path:   /logout
                target: /
            form_login:
                login_path: /login
                check_path: /login_check
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

